#!/bin/bash
path=$(dirname -- "$(readlink -f -- "$0")")

plasmaVersion=$(plasmashell --version | awk -F '[^0-9]+' '{printf $2}')

if [ "$plasmaVersion" = "6" ]; then
        python3 ${path}/tkp.py
    else
        python3 ${path}/tkp-plasma5.py
fi