#!/bin/bash
path=$(dirname -- "$(readlink -f -- "$0")")

plasmaVersion=$(distrobox-enter -- distrobox-host-exec plasmashell --version | awk -F '[^0-9]+' '{printf $2}')

if [ "$plasmaVersion" = "6" ]; then
    distrobox-enter -- python3 ${path}/tkp.py
else
    distrobox-enter -- python3 ${path}/tkp-plasma5.py
fi
